[package]
name = "IntegratePyth"
version = "1.0.0"
authors = ["aladeenb (aladeen@codeandledger.com)"]

[addresses]
integrate_pyth = "_"

pyth = "0x9357e76fe965c9956a76181ee49f66d51b7f9c3800182a944ed96be86301e49f"
deployer = "0x9236893d6444b208b7e0b3e8d4be4ace90b6d17817ab7d1584e46a33ef5c50c9"
wormhole = "0xa3ad2d9c8114b9a4fe97d45b7a9d3c731148d936b0f5dd396fc20a53a11a70da"

[dev-addresses]
integrate_pyth = "0xc1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
rev = "main"
subdir = "target_chains/aptos/contracts"

[dev-dependencies]
